version: '3.8'

services:
  #Nginx Service
  webserver-curios:
    image: nginx:alpine
    container_name: webserver-curios
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - app-curios-network
  
  # Curios App
  app-curios:
    container_name: app-curios
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app-curios
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-curios-network
  
  #MySQL Service
  db-curios:
    image: mysql:5.7.22
    container_name: db-curios
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: curios
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: dostcaraga
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-curios-network

  #Phpmyadmin Service
  phpma-curios:
    depends_on:
       - db-curios
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-curios
    restart: always
    ports:
      - '9292:80'
    environment:
      PMA_HOST: db-curios
    networks:
      - app-curios-network  

#Docker Networks
networks:
  app-curios-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local