version: "3.7"
services:

  # Application Service
  curios-app:
    build:
      args:
        user: curios
        uid: 1000
      context: ./docker
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: curios-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - curios-app-network
  
  # MySQL Service
  curios-db:
    image: mysql:5.7.22
    container_name: curios-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - curios-app-network

  # Nginx Service
  curios-nginx:
    image: nginx:alpine
    container_name: curios-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - curios-app-network

  #Phpmyadmin Service
  curios-phpma:
    depends_on:
      - curios-db
    image: phpmyadmin/phpmyadmin
    container_name: curios-phpma
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: curios-db
    networks:
      - curios-app-network  

# Networks
networks:
  curios-app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local